version: 2
workflows:
  version: 2
  push-to-client:
    jobs:
      - git-slice-pull:
          filters:
            branches:
              ignore: master
      - request_push_branch:
          type: approval
          filters:
            branches:
              ignore: master
      - git-slice-push:
          requires:
            - request_push_branch
            - git-slice-pull
          filters:
            branches:
              ignore: master
  daily-update:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - git-slice-pull


jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout

      - setup_remote_docker:  
          docker_layer_caching: true 
          
      - run: 
          name: install docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: 
          name: build docker image
          command : docker build -t pdfsharpmerge .

  git-slice-push:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd ~ && npm install https://github.com/murcul/git-slice.git
      - run: ~/node_modules/.bin/git-slice push --branch $CIRCLE_BRANCH --message "implementation" --author-name $USERNAME --author-email $EMAIL --password "$PASSWORD"
  git-slice-pull:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd ~ && npm install https://github.com/murcul/git-slice.git
      - run: git config --global user.email "murcul-reviewer@murcul.com"
      - run: git config --global user.name "Murcul Reviewer"
      - run: ~/node_modules/.bin/git-slice pull --username $USERNAME --password "$PASSWORD"
      - run: git reset --hard origin/master && git pull -f origin master && ~/node_modules/.bin/git-slice pull --username $USERNAME --password "$PASSWORD" && git push origin master
